# Generated by Django 4.0.1 on 2022-01-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='extra',
        ),
    ]
