# Generated by Django 4.0.1 on 2022-01-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_remove_contact_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='extra',
            field=models.CharField(default="without default message you cann't add new value", max_length=100),
            preserve_default=False,
        ),
    ]
