# Generated by Django 4.0.1 on 2022-01-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_contact_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
